plugin: amazon.aws.aws_ec2


regions:
  - eu-central-1

filters:
  instance-state-name: running
  "tag:Name": "react-server"

hostnames:
  - public-ip-address

compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'/var/lib/jenkins/test.pem'"

keyed_groups:
  - key: tags.Name
    prefix: name


