pipeline {
    agent any

    environment {
        TERRAFORM_DIR = 'terraform-module/template/stack'
        ANSIBLE_DIR   = 'ansible-project'
    }

    stages {

        stage('Terraform Apply') {
            steps {
                echo "Initializing and applying Terraform..."
                sh """
                    cd $TERRAFORM_DIR
                    terraform init
                    terraform apply -auto-approve
                """
            }
        }

        stage('Wait for EC2') {
            steps {
                echo "Waiting for EC2 to be ready..."
                sh 'sleep 40'
            }
        }

        stage('Ansible Deploy') {
            steps {
                echo "Running Ansible playbook..."
                sh """
                    cd $ANSIBLE_DIR
                    ansible-playbook -i inventory/aws_ec2.yml playbook.yml
                """
            }
        }

        stage('Test Deployment') {
            steps {
                script {
                    def public_ip = sh(
                        script: "cd $TERRAFORM_DIR && terraform output -raw ec2_public_ip",
                        returnStdout: true
                    ).trim()
                    echo "Testing deployment at: http://${public_ip}"
                    sh "curl http://${public_ip}"
                }
            }
        }

    }
}
